---

# PostgreSQL variables

# Define the encrypted SQL password variable outside the nested structures due
# to the issue described in https://stackoverflow
# .com/questions/50770524/ansible-vault-inline-variable-with-to-nice-json
# -unexpected-templating-type-erro
sql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37666261656265663839363630366562653030373038386262363861663338323134663839653266
          3733643431366263633633383539383963646363666366330a666162613833343834623633326261
          38646663613831646164626162613666656232343562633561663835336232623165333331633837
          3135363439373432380a613735636361336331393331613633366565663763396566643061393932
          36623464303835343737323236623739343337316131376531663837653064396534333961316538
          3963656134343530663136366566303833396231306130366136

# PostgreSQL Server Settings.
postgresql_python_library: "python-psycopg2"

# PostgreSQL Server Databases.
postgresql_databases:
  - name: "fightfor"
    port: 5432
  - name: "test"
    port: 5432

# PostgreSQL Users.
postgresql_users:
  - name: "{{ system.user }}"
    password: "{{ sql_password }}"
    port: 5432

# PostgreSQL schemata.
postgresql_schemata:
  - pubmed

# PostgreSQL extensions.
postgresql_extensions:
  - pg_trgm
  - postgis


project:
  name: "pubmed-ingester"

system:
  # User name.
  user: "pubmed_ingester"
  # User group.
  group: "pubmed_ingester"
  # Application directories.
  directories:
    config: "/etc/{{ project.name }}"
    share: "/usr/local/share/{{ project.name }}"
    run: "/var/run/{{ project.name }}"
    log: "/var/log/{{ project.name }}"
    virtual_env: "/usr/local/share/{{ project.name }}/venvs/{{ project.name }}"

# Application Configuration Settings.
config:
  test:
    # General Settings.
    logger_level: DEBUG

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "test"

    # Google Maps API Settings.
    google_maps_api_key: "AIzaSyDp0jjlnAGDCQXNqj075yaUv15t10AsZic"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 1
      worker_class: sync

  dev:
    # General Settings.
    logger_level: DEBUG

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "fightfor"

    # Google Maps API Settings.
    google_maps_api_key: "AIzaSyDp0jjlnAGDCQXNqj075yaUv15t10AsZic"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 1
      worker_class: sync

  prod:
    # General Settings.
    logger_level: INFO

    # PostgreSQL Server Configuration Settings.
    sql_host: "localhost"
    sql_port: 5432
    sql_username: "{{ system.user }}"
    sql_password: "{{ sql_password }}"
    sql_db: "fightfor"

    # Google Maps API Settings.
    google_maps_api_key: "AIzaSyDp0jjlnAGDCQXNqj075yaUv15t10AsZic"

    # Gunicorn Configuration Settings.
    gunicorn:
      host: "127.0.0.1"
      port: 5555
      workers: 4
      worker_class: sync
