---

# Define the encrypted SQL password variable outside the nested structures due
# to the issue described in https://stackoverflow
# .com/questions/50770524/ansible-vault-inline-variable-with-to-nice-json
# -unexpected-templating-type-erro
sql_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33636230323837303735643261366633663631316134396634666335613630393239363065333062
    3330336465663862393832303662326231316264303232380a643634626632623331366535616462
    31343831663636383161316333306335306262643530386139646436663137653437666265626338
    3135336330346537350a663530373865623633373936333533376334303339326163616662663234
    64623736613465656435636233663639373133383061343739383862653631653563323137386463
    3536356264643264623166373763356461663865313639393262

# PostgreSQL Server Settings.
postgresql_python_library: "python-psycopg2"

# PostgreSQL Server Databases.
postgresql_databases:
  - name: "pubmed"
    port: 5432
  - name: "test"
    port: 5432
# PostgreSQL Server Users.
postgresql_users:
  - name: "pubmed_ingester"
    password: "{{ sql_password }}"
    port: 5432

app_pubmed_ingester:

  # Application user settings.
  user: pubmed_ingester
  group: pubmed_ingester

  # Application directories.
  config_dir: /etc/pubmed-ingester
  share_dir: /usr/local/share/pubmed-ingester
  run_dir: /var/run/pubmed-ingester
  log_dir: /var/log/pubmed-ingester
  virtual_env_dir: /usr/local/share/pubmed-ingester/venvs/pubmed-ingester

  # Gunicorn Configuration Settings.
  gunicorn:
    host: "127.0.0.1"
    port: 5555
    workers: 4
    worker_class: sync

  # Application Configuration Settings.
  config:

    dev:
      # General Settings.
      logger_level: DEBUG

      # PostgreSQL Server Configuration Settings.
      sql_host: "localhost"
      sql_port: 5432
      sql_username: "pubmed_ingester"
      sql_password: "{{ sql_password }}"
      sql_db: "pubmed"
    prod:
      # General Settings.
      logger_level: INFO

      # PostgreSQL Server Configuration Settings.
      sql_host: "localhost"
      sql_port: 5432
      sql_username: "pubmed_ingester"
      sql_password: "{{ sql_password }}"
      sql_db: "pubmed"
