"""initial schema

Revision ID: 893449d0071b
Revises: 
Create Date: 2017-11-20 10:10:25.785675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893449d0071b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_texts',
    sa.Column('abstract_text_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('category', sa.Enum('background', 'objective', 'methods', 'results', 'conclusions', 'unassigned', name='abstracttextcategory'), nullable=True),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('abstract_text_id')
    )
    op.create_index(op.f('ix_abstract_texts_category'), 'abstract_texts', ['category'], unique=False)
    op.create_index(op.f('ix_abstract_texts_md5'), 'abstract_texts', ['md5'], unique=True)
    op.create_table('accession_numbers',
    sa.Column('accession_number_id', sa.BigInteger(), nullable=False),
    sa.Column('accession_number', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('accession_number_id')
    )
    op.create_index(op.f('ix_accession_numbers_accession_number'), 'accession_numbers', ['accession_number'], unique=True)
    op.create_index(op.f('ix_accession_numbers_md5'), 'accession_numbers', ['md5'], unique=True)
    op.create_table('affiliations',
    sa.Column('affiliation_id', sa.BigInteger(), nullable=False),
    sa.Column('affiliation_identifier', sa.Unicode(), nullable=True),
    sa.Column('affiliation_identifier_source', sa.Unicode(), nullable=True),
    sa.Column('affiliation', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('affiliation_id')
    )
    op.create_index(op.f('ix_affiliations_md5'), 'affiliations', ['md5'], unique=True)
    op.create_table('authors',
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_identifier', sa.Unicode(), nullable=True),
    sa.Column('author_identifier_source', sa.Unicode(), nullable=True),
    sa.Column('name_first', sa.Unicode(), nullable=True),
    sa.Column('name_last', sa.Unicode(), nullable=True),
    sa.Column('name_initials', sa.Unicode(), nullable=True),
    sa.Column('name_suffix', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_md5'), 'authors', ['md5'], unique=True)
    op.create_table('chemicals',
    sa.Column('chemical_id', sa.BigInteger(), nullable=False),
    sa.Column('num_registry', sa.Unicode(), nullable=True),
    sa.Column('uid', sa.Unicode(), nullable=False),
    sa.Column('chemical', sa.Unicode(), nullable=False),
    sa.CheckConstraint("uid <> ''", name='uid_not_empty'),
    sa.PrimaryKeyConstraint('chemical_id')
    )
    op.create_index(op.f('ix_chemicals_num_registry'), 'chemicals', ['num_registry'], unique=False)
    op.create_index(op.f('ix_chemicals_uid'), 'chemicals', ['uid'], unique=True)
    op.create_table('databanks',
    sa.Column('databank_id', sa.BigInteger(), nullable=False),
    sa.Column('databank', sa.Unicode(length=20), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('databank_id')
    )
    op.create_index(op.f('ix_databanks_databank'), 'databanks', ['databank'], unique=True)
    op.create_index(op.f('ix_databanks_md5'), 'databanks', ['md5'], unique=True)
    op.create_table('descriptors',
    sa.Column('descriptor_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Unicode(), nullable=False),
    sa.Column('descriptor', sa.Unicode(), nullable=False),
    sa.CheckConstraint("uid <> ''", name='uid_not_empty'),
    sa.PrimaryKeyConstraint('descriptor_id')
    )
    op.create_index(op.f('ix_descriptors_descriptor'), 'descriptors', ['descriptor'], unique=True)
    op.create_index(op.f('ix_descriptors_uid'), 'descriptors', ['uid'], unique=True)
    op.create_table('grants',
    sa.Column('grant_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Unicode(), nullable=True),
    sa.Column('acronym', sa.Unicode(length=2), nullable=True),
    sa.Column('agency', sa.Unicode(), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.CheckConstraint("uid <> ''", name='uid_not_empty'),
    sa.PrimaryKeyConstraint('grant_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_grants_md5'), 'grants', ['md5'], unique=True)
    op.create_table('journal_infos',
    sa.Column('journal_info_id', sa.BigInteger(), nullable=False),
    sa.Column('nlmid', sa.Unicode(length=9), nullable=False),
    sa.Column('issn', sa.Unicode(length=9), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('abbreviation', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('journal_info_id')
    )
    op.create_index(op.f('ix_journal_infos_nlmid'), 'journal_infos', ['nlmid'], unique=True)
    op.create_table('journals',
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('issn', sa.Unicode(length=9), nullable=True),
    sa.Column('issn_type', sa.Enum('print', 'electronic', 'undetermined', name='journalissntype'), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('abbreviation', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('journal_id')
    )
    op.create_index(op.f('ix_journals_issn'), 'journals', ['issn'], unique=False)
    op.create_index(op.f('ix_journals_md5'), 'journals', ['md5'], unique=True)
    op.create_table('keywords',
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=True)
    op.create_index(op.f('ix_keywords_md5'), 'keywords', ['md5'], unique=True)
    op.create_table('publication_types',
    sa.Column('publication_type_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Unicode(), nullable=False),
    sa.Column('publication_type', sa.Unicode(), nullable=False),
    sa.CheckConstraint("uid <> ''", name='uid_not_empty'),
    sa.PrimaryKeyConstraint('publication_type_id')
    )
    op.create_index(op.f('ix_publication_types_uid'), 'publication_types', ['uid'], unique=True)
    op.create_table('qualifiers',
    sa.Column('qualifier_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Unicode(), nullable=False),
    sa.Column('qualifier', sa.Unicode(), nullable=False),
    sa.CheckConstraint("uid <> ''", name='uid_not_empty'),
    sa.PrimaryKeyConstraint('qualifier_id')
    )
    op.create_index(op.f('ix_qualifiers_qualifier'), 'qualifiers', ['qualifier'], unique=True)
    op.create_index(op.f('ix_qualifiers_uid'), 'qualifiers', ['uid'], unique=True)
    op.create_table('articles',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('publication_year', sa.SmallInteger(), nullable=False),
    sa.Column('publication_month', sa.SmallInteger(), nullable=True),
    sa.Column('publication_day', sa.SmallInteger(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('publication_model', sa.Enum('print', 'print_electronic', 'electronic', 'electronic_print', 'electronic_ecollection', name='articlepubmodel'), nullable=True),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_volume', sa.Unicode(), nullable=True),
    sa.Column('journal_issue', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('pagination', sa.Unicode(), nullable=True),
    sa.Column('language', sa.Unicode(length=3), nullable=True),
    sa.Column('title_vernacular', sa.Unicode(), nullable=True),
    sa.Column('md5', sa.Binary(), nullable=True),
    sa.CheckConstraint("title <> ''", name='title_not_empty'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.journal_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_articles_md5'), 'articles', ['md5'], unique=True)
    op.create_index(op.f('ix_articles_publication_year'), 'articles', ['publication_year'], unique=False)
    op.create_table('article_abstract_texts',
    sa.Column('article_abstract_text_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('abstract_text_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinance', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['abstract_text_id'], ['abstract_texts.abstract_text_id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('article_abstract_text_id')
    )
    op.create_table('article_author_affiliations',
    sa.Column('article_author_affiliation_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('affiliation_id', sa.BigInteger(), nullable=True),
    sa.Column('ordinance', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.affiliation_id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.PrimaryKeyConstraint('article_author_affiliation_id')
    )
    op.create_table('article_databank_accession_numbers',
    sa.Column('article_databank_accession_number_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('databank_id', sa.BigInteger(), nullable=False),
    sa.Column('accession_number_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['accession_number_id'], ['accession_numbers.accession_number_id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['databank_id'], ['databanks.databank_id'], ),
    sa.PrimaryKeyConstraint('article_databank_accession_number_id')
    )
    op.create_table('article_grants',
    sa.Column('article_grant_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('grant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.grant_id'], ),
    sa.PrimaryKeyConstraint('article_grant_id')
    )
    op.create_table('article_publication_types',
    sa.Column('article_publication_type_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('publication_type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['publication_type_id'], ['publication_types.publication_type_id'], ),
    sa.PrimaryKeyConstraint('article_publication_type_id')
    )
    op.create_table('citations',
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_completion', sa.Date(), nullable=True),
    sa.Column('date_revision', sa.Date(), nullable=True),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_info_id', sa.BigInteger(), nullable=False),
    sa.Column('num_references', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['journal_info_id'], ['journal_infos.journal_info_id'], ),
    sa.PrimaryKeyConstraint('citation_id'),
    sa.UniqueConstraint('pmid')
    )
    op.create_table('citation_chemicals',
    sa.Column('citation_chemical_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('chemical_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.chemical_id'], ),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.citation_id'], ),
    sa.PrimaryKeyConstraint('citation_chemical_id')
    )
    op.create_table('citation_descriptors_qualifiers',
    sa.Column('citation_descriptor_qualifier_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('descriptor_id', sa.BigInteger(), nullable=False),
    sa.Column('is_descriptor_major', sa.Boolean(), nullable=False),
    sa.Column('qualifier_id', sa.BigInteger(), nullable=True),
    sa.Column('is_qualifier_major', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.citation_id'], ),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptors.descriptor_id'], ),
    sa.ForeignKeyConstraint(['qualifier_id'], ['qualifiers.qualifier_id'], ),
    sa.PrimaryKeyConstraint('citation_descriptor_qualifier_id')
    )
    op.create_table('citation_identifiers',
    sa.Column('citation_identifier_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier_type', sa.Enum('doi', 'pii', 'pmcpid', 'pmpid', 'pmc', 'mid', 'sici', 'pubmed', 'medline', 'pmcid', name='articleidentifiertype'), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.citation_id'], ),
    sa.PrimaryKeyConstraint('citation_identifier_id')
    )
    op.create_index(op.f('ix_citation_identifiers_identifier_type'), 'citation_identifiers', ['identifier_type'], unique=False)
    op.create_table('citation_keywords',
    sa.Column('citation_keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.citation_id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.keyword_id'], ),
    sa.PrimaryKeyConstraint('citation_keyword_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citation_keywords')
    op.drop_index(op.f('ix_citation_identifiers_identifier_type'), table_name='citation_identifiers')
    op.drop_table('citation_identifiers')
    op.drop_table('citation_descriptors_qualifiers')
    op.drop_table('citation_chemicals')
    op.drop_table('citations')
    op.drop_table('article_publication_types')
    op.drop_table('article_grants')
    op.drop_table('article_databank_accession_numbers')
    op.drop_table('article_author_affiliations')
    op.drop_table('article_abstract_texts')
    op.drop_index(op.f('ix_articles_publication_year'), table_name='articles')
    op.drop_index(op.f('ix_articles_md5'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_qualifiers_uid'), table_name='qualifiers')
    op.drop_index(op.f('ix_qualifiers_qualifier'), table_name='qualifiers')
    op.drop_table('qualifiers')
    op.drop_index(op.f('ix_publication_types_uid'), table_name='publication_types')
    op.drop_table('publication_types')
    op.drop_index(op.f('ix_keywords_md5'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_journals_md5'), table_name='journals')
    op.drop_index(op.f('ix_journals_issn'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_journal_infos_nlmid'), table_name='journal_infos')
    op.drop_table('journal_infos')
    op.drop_index(op.f('ix_grants_md5'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_descriptors_uid'), table_name='descriptors')
    op.drop_index(op.f('ix_descriptors_descriptor'), table_name='descriptors')
    op.drop_table('descriptors')
    op.drop_index(op.f('ix_databanks_md5'), table_name='databanks')
    op.drop_index(op.f('ix_databanks_databank'), table_name='databanks')
    op.drop_table('databanks')
    op.drop_index(op.f('ix_chemicals_uid'), table_name='chemicals')
    op.drop_index(op.f('ix_chemicals_num_registry'), table_name='chemicals')
    op.drop_table('chemicals')
    op.drop_index(op.f('ix_authors_md5'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_affiliations_md5'), table_name='affiliations')
    op.drop_table('affiliations')
    op.drop_index(op.f('ix_accession_numbers_md5'), table_name='accession_numbers')
    op.drop_index(op.f('ix_accession_numbers_accession_number'), table_name='accession_numbers')
    op.drop_table('accession_numbers')
    op.drop_index(op.f('ix_abstract_texts_md5'), table_name='abstract_texts')
    op.drop_index(op.f('ix_abstract_texts_category'), table_name='abstract_texts')
    op.drop_table('abstract_texts')
    # ### end Alembic commands ###
